[package]
name = "proxxa-shuttleblog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
rocket = { version = "0.5.0", features = ["json"] }
serde = "1.0.193"
serde_json = "1.0.108"
shuttle-rocket = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.26.0"
tracing = "0.1.40"
